apiVersion: v1
kind: Service
metadata:
  name: {{ include "localstack.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "localstack.name" . }}
    helm.sh/chart: {{ include "localstack.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: services
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: services

  selector:
    app.kubernetes.io/name: {{ include "localstack.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}